version: '3'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: 12345678
      MARIADB_DATABASE: gapcure
      MARIADB_USER: root
      MARIADB_PASSWORD: 12345678

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080